""" ----------------------------------------------------------------------------
Copyright (c) 2026, VIDAL & ASTUDILLO Ltda and contributors.
For license information, please see license.txt
By JMVA, VIDAL & ASTUDILLO Ltda.
Version 2026-02-16
-----------------------------------------------------------------------------

It performs several updates to DIAN documents to:
- Update the document with XML information if content is available.
- Move the CUFE from the document name into a dedicated `xml_cufe` field, if
  necessary.
- Rename the documents with a stable autogenerated name.

---------------------------------------------------------------------------- """

import re
import frappe
from frappe.model.naming import make_autoname

from va_app.va_dian.api.dian_document_utils import (
    update_doc_with_xml_info,
)


CUFE_REGEX = re.compile(r"^[A-Fa-f0-9]{64,128}$")
DATE_REGEX = re.compile(r"/private/files/(\d{2})-(\d{2})-(\d{2})\s")


def execute():
    frappe.logger().info("Starting DIAN document renaming migration")

    docs = frappe.get_all(
        "DIAN document",
        fields=["name", "xml", "xml_cufe"],
        order_by="xml asc",
    )

    for row in docs:
        try:
            _process_single_document(row)
        except Exception:
            frappe.log_error(
                title="DIAN document rename migration failed",
                message=f"Failed processing DIAN document {row.name}",
            )
            raise

    frappe.logger().info("DIAN document renaming migration completed")


# -----------------------------------------------------------------------------


def _process_single_document(row):
    """
    Renames a single DIAN document based on XML filename date
    and preserves CUFE safely.
    """

    doc = frappe.get_doc("DIAN document", row.name)

    # ------------------------------------------------------------------
    # Call XML info updater (failure is acceptable)
    # ------------------------------------------------------------------

    try:
        update_doc_with_xml_info(doc)
    except Exception as e:
        frappe.log_error(
            title="DIAN XML info update failed",
            message=f"update_doc_with_xml_info failed for {doc.name} with error: {e}",
        )

    # ------------------------------------------------------------------
    # Preserve CUFE if name looks like CUFE and xml_cufe is empty
    # ------------------------------------------------------------------

    if not doc.xml_cufe and CUFE_REGEX.match(doc.name):
        doc.xml_cufe = doc.name

    # ------------------------------------------------------------------
    # Extract year from xml filename
    # Expected: /private/files/YY-MM-DD xxx
    # ------------------------------------------------------------------

    if not doc.xml:
        frappe.logger().warning(
            f"Skipping {doc.name}: xml field is empty"
        )
        return

    match = DATE_REGEX.search(doc.xml)
    if not match:
        frappe.logger().warning(
            f"Skipping {doc.name}: cannot extract date from xml path ({doc.xml})"
        )
        return

    yy, mm, dd = match.groups()
    year = f"20{yy}"

    # ------------------------------------------------------------------
    # Generate new name
    # ------------------------------------------------------------------

    new_name = make_autoname(f"DIAN-DOC-.{year}.-.#####")

    # Already correctly named → skip rename
    if doc.name == new_name:
        return

    # ------------------------------------------------------------------
    # Rename FIRST (updates links safely)
    # ------------------------------------------------------------------

    doc.rename(new_name)

    # ------------------------------------------------------------------
    # Save any changes
    # ------------------------------------------------------------------

    doc.save(ignore_permissions=True)

    frappe.logger().info(
        f"Migrated DIAN document: {row.name} → {new_name}"
    )
