""" ----------------------------------------------------------------------------
Copyright (c) 2026, VIDAL & ASTUDILLO Ltda and contributors.
For license information, please see license.txt
By JMVA, VIDAL & ASTUDILLO Ltda.
Version 2026-02-15
-----------------------------------------------------------------------------

** TODO **
DO NOT USE THIS YET.
It renames the documents with an equal name, and still relies in the content
of the XML extraction, which is not always available!

Migration: Move CUFE from document name into `cufe` field

This patch migrates legacy DIAN documents where:
  - name == CUFE
  - cufe field is empty

Result:
  - name becomes stable autogenerated name
  - cufe stores the original CUFE

Safe to re-run (idempotent).
---------------------------------------------------------------------------- """

import re
import frappe


CUFE_REGEX = re.compile(r"^[A-Fa-f0-9]{64,128}$")


def execute():
    frappe.logger().info("Starting CUFE name migration")

    docs = frappe.get_all(
        "DIAN document",
        fields=["name", "cufe"],
    )

    for row in docs:
        name = row.name
        cufe = row.cufe

        # Already migrated → skip
        if cufe:
            continue

        # Name does not look like CUFE → skip
        if not CUFE_REGEX.match(name):
            continue

        try:
            _migrate_single_document(name)
        except Exception:
            frappe.log_error(
                title="CUFE migration failed",
                message=f"Failed migrating DIAN document {name}",
            )
            raise

    frappe.logger().info("CUFE name migration completed")


# -----------------------------------------------------------------------------


def _migrate_single_document(old_name: str):
    """
    Migrates one DIAN document safely.
    """

    doc = frappe.get_doc("DIAN document", old_name)

    # Defensive check
    if doc.cufe:
        return

    # Preserve CUFE
    doc.cufe = old_name

    # Generate new stable name
    new_name = frappe.model.naming.make_autoname("DIAN-DOC-.YYYY.-.#####")

    # Rename document FIRST (this updates links safely)
    doc.rename(new_name)

    # Save CUFE field
    doc.save(ignore_permissions=True)

    frappe.logger().info(
        f"Migrated DIAN document: {old_name} → {new_name}"
    )
